export const COUNTER_CHANGE = 'COUNTER_CHANGE';

export const TEST_FETCH_DATA_REQUEST = 'TEST_FETCH_DATA_REQUEST';
export const TEST_FETCH_DATA_SUCCESS = 'TEST_FETCH_DATA_SUCCESS';
export const TEST_FETCH_DATA_FAILURE = 'TEST_FETCH_DATA_FAILURE';